name: Build and Export Docker Images for ARM64

on:
  push:
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TERM: xterm

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      # Set up Docker Buildx for multi-architecture support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Set up multi-platform build environment (specifically ARM64)
      - name: Set up multi-platform build
        run: |
          docker buildx create --use

      # Build Docker image for ARM64 and export as tar directly as an artifact
      - name: Build ARM64 Docker image and export as tar
        run: |
          # Build the image for ARM64 architecture
          docker buildx build \
            --platform linux/arm64 \
            -t myusername/myapp:arm64-${{ github.sha }} \
            .

          # Export the image to a tar file and directly upload as artifact
          docker save myusername/myapp:arm64-${{ github.sha }} -o myapp-arm64-${{ github.sha }}.tar

      # Upload the tar file directly as an artifact
      - name: Upload ARM64 Docker image tar as artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-arm64-image
          path: myapp-arm64-${{ github.sha }}.tar

      # Optionally, list the tar file in the current working directory for debugging
      - name: List current directory contents (debugging)
        run: |
          echo "Listing current directory contents:"
          ls -l
