name: Build and Export Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up QEMU for ARM64 emulation
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 4: Extract metadata for Docker images
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}

    # Step 5: Build Docker images
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: false # Set this to false to prevent pushing to a registry
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Step 6: Save images as tar files
    - name: Save Docker images
      run: |
        mkdir -p images
        for tag in ${{ steps.meta.outputs.tags }}; do
          image_name=$(echo "$tag" | cut -d':' -f1)
          docker save -o "images/$(basename $image_name).tar" "$tag"
        done

    # Step 7: Upload images as artifacts
    - name: Upload images as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: docker-images
        path: images/
