name: Build and Export ARM64 Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-export-arm64:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up QEMU for ARM64 emulation
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/arm64

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 4: Build and Export Docker Images
    - name: Build and Export Docker Images
      run: |
        mkdir -p images
        services=$(docker-compose config --services)

        for service in $services; do
          # Build the image for ARM64
          docker-compose build --platform linux/arm64 "$service"
          
          # Export the image as a tar file
          image_name=$(docker-compose config | yq ".services[\"$service\"].image // \"$service\"")
          docker save -o "images/$image_name.tar" "$image_name:latest"
        done

    # Step 5: Upload images as artifacts
    - name: Upload Exported Images
      uses: actions/upload-artifact@v3
      with:
        name: docker-images
        path: images/
