name: Test scripts and build Docker images

on:
  push:
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Apply Docker Compose CI overrides
        run: ln -s .github/compose.ci.yml compose.override.yml

      - name: Run the setup script
        run: ./setup.sh --server-ip 127.0.0.1 --force --verbose

      - name: Test starting the servers
        run: |
          docker compose up -d
          echo Waiting for 60 seconds...
          sleep 60
          docker compose ps -a
          docker compose logs
          # Fail if any containers exited
          ! docker compose ps -a | grep Exited 

      - name: Save Docker containers to tar files
        run: |
          mkdir -p docker_exports
          docker ps -q | while read container_id; do
            container_name=$(docker inspect --format='{{.Name}}' $container_id | sed 's|/||')
            docker export $container_id > docker_exports/$container_name.tar
          done

      - name: Upload Docker container tar files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-container-exports
          path: docker_exports
